# Finnish
- id: randbpe-eng-fin-big
  langs: eng-fin
  desc: "English - Finnish, mimics WMT 2019 News Task"
  train:
    - Statmt-europarl-9-fin-eng
    - ParaCrawl-paracrawl-9-eng-fin
    - Tilde-rapid-2016-eng-fin
  dev:
    # eval on eng-fin newsdev/test 2015-2017
    - Statmt-newsdev_enfi-2015-eng-fin
    - Statmt-newstest_enfi-2017-eng-fin
    - Statmt-newstest_enfi-2016-eng-fin
  test:
    - Statmt-newstest_enfi-2019-eng-fin

# Estonian
- id: randbpe-eng-est-big
  langs: eng-est
  desc: "English - Estonian, mimics WMT 2018 News Task"
  train:
    - ParaCrawl-paracrawl-9-eng-est
    - Statmt-ccaligned-1-eng-est_EE
    - Statmt-europarl-7-est-eng
    - Tilde-rapid-2016-eng-est
  dev:
    - Statmt-newsdev_enet-2018-eng-est
  test:
    - Statmt-newstest_enet-2018-eng-est
